name: "SSH Command"
description: "Run a command via SSH"
inputs:
  host:
    description: "SSH host address or IP to connect to."
    required: true
  port:
    description: "SSH port number for the connection."
    required: true
  username:
    description: "SSH username for authentication on the remote server."
    default: ${{ secrets.SSH_USER }}
    required: true
  password:
    description: "SSH password for authentication (use secrets for sensitive data)."
    default: ${{ secrets.SSH_PASSWORD }}
    required: true
  script:
    description: "Commands to execute on the remote server (inline script string)."
    required: true

  outputs:
    stdout:
      description: "Standard output of the executed commands when capture_stdout is enabled."
      value: ${{ steps.entrypoint.outputs.stdout }}

  runs:
    using: "composite"
    steps:
      - name: Execute SSH command
        uses: appleboy/ssh-action@v1.0.3
        id: entrypoint
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          port: ${{ inputs.port }}
          script: ${{ inputs.script }}